name: Deploy
on:
  push:
    branches: [main, exam/cicde-francois]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to staging (Render)
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK}}"
          echo "Deployed to staging"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to production
        run: echo "Production deployment approved and done"